service: romicusblr-portfolio

provider:
  name: aws
  profile: rm_aws
  runtime: nodejs16.x
  stage: dev
  region: eu-central-1
  memorySize: 128

functions:
  headers:
    handler: headers.handler
    architecture: x86_64
  api:
    handler: index.handler
    architecture: arm64
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
